# Generated by Django 3.2 on 2023-09-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='详细信息')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
                ('count', models.PositiveBigIntegerField(default=0, verbose_name='库存')),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='register_date',
            field=models.DateField(auto_now=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.PositiveIntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(db_index=True, max_length=16, verbose_name='姓名'),
        ),
    ]
